size (1000,600); 
background (0,0,0);
println("helooooo!!!!!!!!!!!");
print ("i am em otori!!!");
print ("i liek playimg video game!!!!!!!!!");
fill (255,0,0);
text ("video games mario in real life 2014",30,67);
fill (0,255,0);
text ("mario from mario franchise comes to chicago??",89,370);
fill (0,0,255);
text ("Peter Griffin fights iconic character 'the grand dad' from grand dad video game franchise in this weeks new episode of family guy! on fox!",300,289);
